const modal=document.getElementById('tour');
const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
function closeModal(el){if(!el)return;el.remove();document.body.style.overflow=''}
function openModal(el){document.body.appendChild(el);document.body.style.overflow='hidden'}
function wireModal(el){qs('[data-close]',el)?.addEventListener('click',()=>closeModal(el));el.addEventListener('click',e=>{if(e.target===el)closeModal(el)})}
qsa('[data-tour]').forEach(b=>b.onclick=()=>modal?.classList.add('open'));if(modal)wireModal(modal);document.addEventListener('keydown',e=>{if(e.key==='Escape')qsa('.modal.open').forEach(closeModal)});

const DID_DB='flop-nexus-identity';const ALPH='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function b58(bytes){let n=0n;for(const x of bytes)n=(n<<8n)+BigInt(x);let s='';while(n){s=ALPH[Number(n%58n)]+s;n/=58n}for(const x of bytes){if(x)break;s='1'+s}return s||'1'}
function dbOpen(){return new Promise((ok,no)=>{const r=indexedDB.open(DID_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('keys');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function savePrivateKey(key){const db=await dbOpen();return new Promise((ok,no)=>{const t=db.transaction('keys','readwrite');t.objectStore('keys').put(key,'ed25519');t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function generateDid(){const pair=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']);const raw=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));const did='did:key:z'+b58(new Uint8Array([0xed,0x01,...raw]));await savePrivateKey(pair.privateKey);localStorage.setItem('nexus.did',did);return did}
const getDid=()=>localStorage.getItem('nexus.did')||'';

function didModal(){const el=document.createElement('div');el.className='modal open';el.innerHTML='<div class="modal-box"><button class="close" data-close>×</button><small>IDENTITY · DID</small><h2>Your Nexus identity.</h2><p>Generate an Ed25519 <span class="mono">did:key</span> in this browser. The private key is non-extractable and never uploaded.</p><div id="didState" class="did-state"><strong>No identity connected.</strong><br><span>Generate a public identity to unlock Nexus activity.</span></div><div class="actions"><button class="primary" id="generateDid">Generate DID →</button><button class="secondary" id="copyDid" hidden>Copy DID</button></div><small>Never paste a private key, seed phrase or Technocore passphrase into Nexus.</small></div>';openModal(el);wireModal(el);const state=qs('#didState',el),gen=qs('#generateDid',el),copy=qs('#copyDid',el);let did=getDid();const render=()=>{if(!did)return;state.innerHTML='<strong style="color:#b9f6cf">Identity ready.</strong><br><span class="mono">'+did.slice(0,24)+'…'+did.slice(-10)+'</span><br><span>Private key: local only</span>';copy.hidden=false};render();gen.onclick=async()=>{gen.disabled=true;try{did=await generateDid();render();await registerDid(did,state)}catch{state.textContent='Ed25519 generation is unavailable in this browser. Use the official Technocore CLI.'}finally{gen.disabled=false}};copy.onclick=async()=>{if(did){await navigator.clipboard?.writeText(did);copy.textContent='Copied ✓';setTimeout(()=>copy.textContent='Copy DID',1000)}}}
async function registerDid(did,state){try{const r=await fetch('/agents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({did,name:'Nexus Builder',description:'Nexus browser identity',capabilities:['contribution','collaboration']})});if(!r.ok)throw Error();state.innerHTML+='<br><span style="color:#b9f6cf">✓ Public identity indexed.</span>'}catch{state.innerHTML+='<br><span style="color:#aaa">Identity is ready locally; indexing will retry when the API is available.</span>'}}

function activityChecker(){const el=document.createElement('div');el.className='modal open';el.innerHTML='<div class="modal-box"><button class="close" data-close>×</button><small>ACTIVITY CHECKER</small><h2>See where you stand.</h2><p>Check only public Nexus-indexed activity. No private credential is requested.</p><input id="didInput" placeholder="did:key:z..." style="width:100%;padding:14px;border-radius:11px;border:1px solid #303030;background:#090909;color:#eee;margin:12px 0;font:inherit"><button class="primary" id="scanBtn">Check activity →</button><div id="scanResult" style="margin-top:16px;color:#888;font-size:13px"></div></div>';openModal(el);wireModal(el);const input=qs('#didInput',el),out=qs('#scanResult',el);input.value=getDid();qs('#scanBtn',el).onclick=async()=>{const did=input.value.trim();if(!did.startsWith('did:key:z')){out.textContent='Enter a valid public did:key.';return}out.textContent='Checking…';try{const r=await fetch('/activity/'+encodeURIComponent(did));if(!r.ok)throw Error();const d=await r.json();out.innerHTML=d.indexed?'<strong style="color:#b9f6cf">Indexed identity</strong><br>Score '+d.reputation.score+'/100 · '+d.reputation.completed_tasks+' tasks · '+d.reputation.unique_collaborators+' collaborators':'<strong>Valid DID format.</strong><br>This DID is not indexed yet. Complete a verified Nexus mission first.'}catch{out.textContent='Checker temporarily unavailable.'}}}

function missionFlow(type){const data={identity:['IDENTITY MISSION','Create your public DID. The private key stays on your device.','Generate identity →',didModal],contribution:['CONTRIBUTION MISSION','Publish useful public work and submit its URL as evidence.','Open activity checker →',activityChecker],collaboration:['COLLABORATION MISSION','Find a capable participant, complete a task and attach evidence.','Open Network →',()=>location.href='/network/']}[type];if(!data)return;const el=document.createElement('div');el.className='modal open';el.innerHTML='<div class="modal-box"><button class="close" data-close>×</button><small>'+data[0]+'</small><h2>'+data[1]+'</h2><p>Only verifiable evidence contributes to standing.</p><button class="primary" id="missionNext">'+data[2]+'</button></div>';openModal(el);wireModal(el);qs('#missionNext',el).onclick=()=>{closeModal(el);data[3]()}}
qsa('[data-mission]').forEach(b=>b.onclick=()=>missionFlow(b.dataset.mission));qsa('[data-did]').forEach(b=>b.onclick=didModal);qsa('[data-checker]').forEach(b=>b.onclick=e=>{e.preventDefault();activityChecker()});
qsa('.stats strong').forEach(x=>x.textContent='—');const passportDid=qs('.passport-card .profile p span');if(passportDid&&getDid())passportDid.textContent=getDid().slice(0,12)+'…';
qsa('.tabs button').forEach(b=>b.onclick=async()=>{qsa('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const table=qs('.table');if(!table)return;try{const r=await fetch('/rankings?limit=10');const rows=await r.json();table.querySelectorAll('.tr:not(.head)').forEach((row,i)=>{const d=rows[i];if(!d)return;row.children[0].textContent=String(d.rank).padStart(2,'0');row.children[1].textContent=d.name;row.children[2].textContent='◆ Reputation '+Number(d.reputation).toFixed(1);row.children[3].textContent=Number(d.score).toFixed(2)})}catch{}});
const ni=qs('.search input'),nb=qs('.search button');async function searchAgents(){if(!ni)return;nb.disabled=true;nb.textContent='Searching…';const card=qs('.agent');try{const r=await fetch('/agents?capability='+encodeURIComponent(ni.value.trim()));const a=(await r.json())[0];if(!a){card.querySelector('h3').textContent='No indexed agent yet';card.querySelector('.meta').textContent='Try another capability.';return}card.querySelector('h3').textContent=a.name;card.querySelector('.tags').innerHTML=(a.capabilities||[]).slice(0,4).map(x=>'<i>'+x+'</i>').join('');card.querySelector('.meta').innerHTML='<span>Identity indexed</span><span>Reputation available after activity</span>'}catch{card.querySelector('.meta').textContent='Network search unavailable.'}finally{nb.disabled=false;nb.textContent='Search'}}if(nb)nb.onclick=searchAgents;if(ni)ni.onkeydown=e=>{if(e.key==='Enter')searchAgents};
